mongo:
  uri: "mongodb://localhost:27017"
  db: "mydb"
  collection: "podcasts"
  gridfs_bucket: "fs_audio"

elasticsearch:
  url: "http://localhost:9200"
  indexes:
    files_metadata: "files-metadata"
    hostility_results: "hostility-results"

kafka:
  bootstrap_servers: "localhost:9092"
  # Polling timeout for consumers (ms)
  consumer_timeout_ms: 1000
  # Number of records processed before committing offsets
  consumer_batch_size: 50
  topics:
    raw_metadata: "raw-metadata"
    transcribed_content: "transcribed-content"
    hostility_results: "hostility-results"

files:
  path: "C:\\podcasts"
