mongo:
  uri: "mongodb://localhost:27017"
  db: "mydb"
  collection: "podcasts"
  gridfs_bucket: "fs_audio"


kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    raw_metadata: "raw-metadata"
    transcription_ready: "transcription-ready"

files:
  path: "C:\\podcasts"

