mongo:
  uri: "mongodb://localhost:27017"
  db: "mydb"
  collection: "podcasts"


kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    raw_metadata: "raw-metadata"

files:
  path: "C:\\podcasts"